repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Replace with the latest Black version
    hooks:
      - id: black
        args: [--skip-string-normalization]  # Preserve single quotes

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Replace with the latest Flake8 version
    hooks:
      - id: flake8